# 使用官方 Python 映像
FROM python:3.11-slim

# 安裝必要的構建工具和依賴項
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    gfortran \
    libatlas-base-dev \
    libblas-dev \
    liblapack-dev

# 設定工作目錄為 /app
WORKDIR /app

# 複製當前目錄內容到容器的 /app
COPY . /app

# 安裝特定版本的 numpy
RUN pip install --no-cache-dir numpy==1.21.2

# 安裝 requirements.txt 中指定的任何需要的包
RUN pip install --no-cache-dir -r requirements.txt

# 將端口 5000 開放給外部世界
EXPOSE 5000

# 定義環境變量
ENV NAME World

# 當容器啟動時運行 app.py
CMD ["python", "main.py"]
